apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: tanejb-dev
  labels:
    app: mongo
    app.kubernetes.io/part-of: cinema-microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
