apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Developer Sandbox: use your personal project (e.g. tanejb-dev), not a new namespace.
namespace: tanejb-dev
resources:
  - 01-configmap-common.yaml
  - 02-secret.yaml
  - infra/mongo-pvc.yaml
  - infra/mongo.yaml
  - infra/rabbitmq.yaml
  - services/movies.yaml
  - services/users.yaml
  - services/screenings.yaml
  - services/reservations.yaml
  - services/users-worker.yaml
  - gateways/api-gateway-web.yaml
  - gateways/api-gateway-mobile.yaml
  - routes/api-gateway-web-route.yaml
  - routes/api-gateway-mobile-route.yaml
  - frontend/web-frontend.yaml
